<?php
$lb=new Core_Model_Language(); 
$wp=new Core_WebsiteSettings();
?>
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
  <meta charset="utf-8" />
  <title>Login page</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport" />
  <meta content="" name="description" />
  <meta content="" name="author" />
  <link href="<?php echo $wp->websiteUrl; ?>assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
  <link href="<?php echo $wp->websiteUrl; ?>assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
  <link href="<?php echo $wp->websiteUrl; ?>css/theme/style.css" rel="stylesheet" />
   <link href="<?php echo $wp->websiteUrl; ?>css/theme/style_default.css" rel="stylesheet" />
   <link href="<?php echo $wp->websiteUrl; ?>css/theme/alertify.core.css" rel="stylesheet" />
   <link href="<?php echo $wp->websiteUrl; ?>css/theme/alertify.default.css" rel="stylesheet" />
   <link href="<?php echo $wp->websiteUrl; ?>css/theme/style_responsive.css" rel="stylesheet" />
   <link href="<?php echo $wp->websiteUrl; ?>css/theme/style_default.css" rel="stylesheet" id="style_color" />
   <link href="<?php echo $wp->websiteUrl; ?>assets/fancybox/source/jquery.fancybox.css" rel="stylesheet" />
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<body id="login-body">
  

  <!-- BEGIN LOGIN -->
  <div id="login">
    <div class="login-header">
      <!-- BEGIN LOGO -->
      <div id="logo" class="center" style=" color: rgb(10, 14, 114); font-size:25px;">
          Admin Panel
      </div>
      <!-- END LOGO -->
  </div>
    <!-- BEGIN LOGIN FORM -->
    <form id="loginform" name="loginform" class="form-vertical no-padding no-margin" method="post" action="index.php">
      <div class="lock">
          <i class="icon-lock"></i>
      </div>      
      <div class="control-wrap">
          <h4>User Login</h4>
	  <div id="error_div" name="error_div" style="color: red;"></div>
          <div class="control-group">
              <div class="controls">
                  <div class="input-prepend">
                      <span class="add-on"><i class="icon-user"></i></span>
                      <input id="username" name="username" type="text" placeholder="Username" />
                  </div>
              </div>
          </div>
          <div class="control-group">
              <div class="controls">
                  <div class="input-prepend">
                      <span class="add-on"><i class="icon-key"></i></span>
                      <input id="userpassword" name="userpassword" type="password" placeholder="Password" />
                  </div>
                  <div class="mtop10">
                      
                      <div class="block-hint pull-right">
                          <!--<a href="javascript:;" class="" id="forget-password">Forgot Password?</a>-->
                      </div>
                  </div>

                  <div class="clearfix space5"></div>
              </div>

          </div>
      </div>

      <input type="button" id="login-btn" class="btn btn-block login-btn" value="Login" onclick="return validatelogin();"/>
    </form>    
    <script type="text/javascript">
      function validatelogin()
      {
        var formdata = $("form" ).serialize();
	$.ajax({
		url : "login.php",
		type : "POST",
		dataType : "html",
		data : formdata,
		success : function (html)
		{
			if(html!="success")
			{
			    alert(html);
				$("#error_div").html(html)
				return false;
			}
                        else
                        {
                          window.location.href = 'index.php';
                          return true;
                        }
		}
	});
      }
    </script> 
    <!-- END LOGIN FORM -->        
    <!-- BEGIN FORGOT PASSWORD FORM -->
    <form id="forgotform" class="form-vertical no-padding no-margin hide" action="login.php">
      <p class="center">Enter your e-mail address below to reset your password.</p>
      <div class="control-group">
        <div class="controls">
          <div class="input-prepend">
            <span class="add-on"><i class="icon-envelope"></i></span><input id="input-email" type="text" placeholder="Email"  />
          </div>
        </div>
        <div class="space20"></div>
      </div>
      <input type="button" id="forget-btn" class="btn btn-block login-btn" value="Submit" />
    </form>
    <!-- END FORGOT PASSWORD FORM -->
  </div>
  <!-- END LOGIN -->
  <!-- BEGIN COPYRIGHT -->
  
  <!-- END COPYRIGHT -->
  <!-- BEGIN JAVASCRIPTS -->
  <script src="js/jquery-1.8.3.min.js"></script>
  <script src="assets/bootstrap/js/bootstrap.min.js"></script>
  <script src="js/jquery.blockui.js"></script>
  <script src="js/scripts.js"></script>
  <script>
    jQuery(document).ready(function() {     
      App.initLogin();
    });
  </script>
  <!-- END JAVASCRIPTS -->
</body>
<!-- END BODY -->
</html>