<?php    
    $type="checkbox";
    if($this->_readonly==1)
    {
        $type="hidden";
    }
?>
<div class="checker <?php echo $type;?>" id="uniform-<?php echo $this->_idName; ?>">
    <span>
        <input class="input-large" type="<?php echo $type;?>" id="<?php echo $this->_idName; ?>" name="<?php echo $this->_idName; ?>" value="<?php echo $this->_Value; ?>"  />        
    </span>
</div>
<?php
        if($this->_readonly==1)
        {
            if($this->_Value==1)
            {
                echo "Yes";
            }
            else
            {
                echo "No";
            }

        }
    ?>