<?php    
    $type="checkbox";
    $class="";
    if($this->_readonly==1)
    {
        $type="hidden";
        $class.=" ".$type;
    } 
    $checked=" ";
    if($this->_Value==1)
    {
        $checked=" checked ";
    }    
?>
<div class="checker <?php echo $class; ?>" id="uniform-<?php echo $this->_idName; ?>">
   
        <input class="input-large" type="<?php echo $type;?>" id="<?php echo $this->_idName; ?>" name="<?php echo $this->_idName; ?>" value="1"  <?php echo $checked; ?> />        
    
</div>
<?php
        if($this->_readonly==1)
        {
            if($this->_Value==1)
            {
                echo "Yes";
            }
            else
            {
                echo "No";
            }

        }
    ?>