<div class="control" id="value_user_image">
    <a href="javascript: void(0);" target="_center" onclick="return popup('http://localhost/smartcode/uploads/smartcode/userimages/1426309871_nature.jpg','notes')">
        <img src="uploads/smartcode/userimages/small_1426309871_nature.jpg" style=" max-width: 250px; max-width: 200px;">
    </a>
    <div class="checker" id="uniform-check_user_image">
        <span><input type="checkbox" name="check_user_image" id="check_user_image" value="1" style="opacity: 0;"></span>
    </div> Remove File<input type="file" name="user_image" id="user_image" value="">
    <span class="control" id="error_user_image">
        
    </span></div>