<?php    
    if($this->_multiedit==1)
    {        
        if(key_exists($this->_pkName."pk", $this->_record))
        {
            $primarykeyValue=$this->_record[$this->_pkName."pk"];
        }
        else
        {
            $primarykeyValue=$this->_record[$this->_pkName];
        }       
        ?>
        
        <input type="text" id="<?php echo $this->_nodeName."_".$primarykeyValue."_".$this->_idName; ?>" name="<?php echo $this->_nodeName."_save[".$primarykeyValue."][".$this->_idName."]"; ?>" value="<?php echo $this->_Value; ?>" />        
    
        
        <?php
    }
    else
    {
        echo $this->_Value;  
    }
?>