<div class="container-fluid">
   <div class="row-fluid">
      <div class="span12">
         <div class="widget">
            <div class="widget-title">
               <h4><i class="icon-reorder"></i>ADD</h4>
               <span class="tools">
               <a href="javascript:;" class="icon-chevron-down"></a>
               </span>
            </div>
            <div class="widget-body">
               <div>
                   <form id="action_type" name="<?php echo $this->_nodeName; ?>" class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                     <input type="hidden" id="parentnode" name="parentnode" value="">
                     <input type="hidden" id="parentidvalue" name="parentidvalue" value="">
                     <input type="hidden" id="resultchange" name="resultchange" value="1">
                     <div id="error_div" name="error_div" style="color: red;font-weight: bold;"></div>    
                     <?php                                    
                        if(count($this->_showAttributes)>0)
                        {
                            foreach($this->_showAttributes as $FieldName)
                            {
                                ?>
                                <div class="control-group" id="row_<?php echo $FieldName; ?>">
                                    <lable class="control-label"><span id="label_<?php echo $FieldName; ?>"><?php echo $this->getLabel($FieldName); ?></span><span id="req_name"><img src="http://localhost/smartcode/img/required_field.gif"></span></lable>
                                    <div class="control" id="value_<?php echo $FieldName; ?>">
                                       <div class="controls">
                                           
                                           <input class="input-large" type="text" id="<?php echo $FieldName; ?>" name="<?php echo $FieldName; ?>" value="" required="">
                                       </div>
                                       <span class="control" id="error_<?php echo $FieldName; ?>"></span>
                                    </div>
                                </div>
                    <?php
                            }
                        }
                    ?>
                                          
                     <div class="form-actions">
                        <input type="hidden" id="formsubmit" name="formsubmit" value="0">
                        <input type="hidden" id="validate_value" name="validate_value" value="1">	
                        <button type="submit" id="saveandclose" name="saveandclose" class="btn btn-small btn-success" onclick="return getformsubmit();"> <i class="icon-ok"></i> Save and Close</button>
                        <button type="button" id="refreshsaveandclose" name="refreshsaveandclose" class="btn btn-small btn-inverse" style="display:none;" onclick="removedisable()" ;=""> <i class="icon-refresh icon-white"></i> Refresh Save and Close</button>
                        <a href="<?php echo $this->_websiteHostUrl; ?> ">
                            <button style="margin-left:4px;" type="button" class="btn btn-small btn-warning">  
                                <i class=" icon-remove"></i> Cancel
                            </button>
                        </a>	
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
