<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <div class="widget">
                    <div class="widget-title">
                            <h4><i class="icon-reorder"></i><?php echo $this->_currentAction;?></h4>
                                                    <span class="tools">
                                                    <a href="javascript:;" class="icon-chevron-down"></a>
                                                    </span>
                    </div>
                    <div class="widget-body" >
                        <?php
                            $this->loadLayout("grid.phtml");
                        ?>
                    </div>
            </div>
        </div>
    </div>
</div>